import { User, ViewType } from '../types';

const ADMIN_VISUALIZATION_VIEWS: ViewType[] = [
  'dashboard',
  'moduleGovernance',
  'architecture',
  'dataDictionary',
  'operations',
  'flows',
  'screenFlows',
  'eventsMatrix',
  'systemConfig',
  'producerPortal',
  'technicianPortal',
  'investorPortal',
  'supplierPortal',
  'integratorPortal',
  'operatorPortal',
  'finance',
  'stock',
  'commercial',
  'logistics',
  'logisticsPortal',
  'auctionPortal',
  'auctionBidControl',
  'legal',
  'propertyRegistration',
  'operationalAction',
  'contracts',
  'sales',
  'financials',
  'accountControl',
  'management',
  'futureMarket',
  'workforce',
  'workforceEmployees',
  'workforceTime',
  'workforcePayroll',
  'workforcePpe',
  'workforceOperatorAccess',
  'publicMarket',
  'aiAnalysis',
  'liveHandling',
  'integrations',
  'fieldOperations',
  'reports',
  'carbonMarket',
  'customInputRequest',
  'milkControl',
  'mobileApp',
  'marketplace',
  'screenFlows',
  'externalMarketplace',
];

export const roleAccessConfig: Record<User['role'], ViewType[]> = {
  Produtor: [
    'dashboard',
    'producerPortal',
    'stock',
    'commercial',
    'logistics',
    'logisticsPortal',
    'milkControl',
    'propertyRegistration',
    'contracts',
    'sales',
    'financials',
    'accountControl',
    'management',
    'futureMarket',
    'workforce',
    'workforceEmployees',
    'workforceTime',
    'workforcePayroll',
    'workforcePpe',
    'workforceOperatorAccess',
    'liveHandling',
    'integrations',
    'fieldOperations',
    'reports',
    'carbonMarket',
    'customInputRequest',
    'marketplace',
    'screenFlows',
    'externalMarketplace',
    'moduleGovernance',
  ],
  'Produtor de Sementes': ['dashboard', 'stock', 'reports', 'integrations', 'financials', 'marketplace', 'screenFlows', 'externalMarketplace'],
  'T\u00E9cnico': ['dashboard', 'technicianPortal', 'producerPortal', 'liveHandling', 'mobileApp', 'operatorPortal', 'milkControl', 'marketplace', 'screenFlows', 'externalMarketplace'],
  Investidor: ['dashboard', 'investorPortal', 'finance', 'screenFlows', 'externalMarketplace'],
  Fornecedor: ['dashboard', 'supplierPortal', 'stock', 'logistics', 'logisticsPortal', 'integrations', 'marketplace', 'screenFlows', 'externalMarketplace'],
  Operador: ['operatorPortal', 'auctionPortal', 'auctionBidControl', 'liveHandling', 'mobileApp', 'milkControl', 'marketplace', 'screenFlows', 'externalMarketplace'],
  Leiloeiro: ['dashboard', 'auctionPortal', 'auctionBidControl', 'sales', 'reports', 'commercial', 'marketplace', 'screenFlows', 'externalMarketplace'],
  Gestor: [...ADMIN_VISUALIZATION_VIEWS],
  Integradora: ['dashboard', 'integratorPortal', 'contracts', 'financials', 'logistics', 'logisticsPortal', 'integrations', 'commercial', 'screenFlows', 'externalMarketplace', 'moduleGovernance'],
  'Gestor de Trafego': [
    'dashboard',
    'supplierPortal',
    'logistics',
    'logisticsPortal',
    'financials',
    'operations',
    'eventsMatrix',
    'integrations',
    'legal',
    'screenFlows',
    'externalMarketplace',
  ],
  Administrador: [...ADMIN_VISUALIZATION_VIEWS],
};

export const canAccessView = (user: User, view: ViewType): boolean => {
  const roleViews = roleAccessConfig[user.role] ?? [];
  return roleViews.includes(view);
};
