// ===== EVENTOS =====
export enum EventType {
  STOCK_DEPOSIT = "STOCK_DEPOSIT",
  STOCK_WITHDRAW = "STOCK_WITHDRAW",
  STOCK_APPLY = "STOCK_APPLY",
  STOCK_TRANSFER = "STOCK_TRANSFER",

  MARKETPLACE_VIEW = "MARKETPLACE_VIEW",
  MARKETPLACE_RESERVE = "MARKETPLACE_RESERVE",
  MARKETPLACE_CANCEL = "MARKETPLACE_CANCEL",
  MARKETPLACE_FULFILL = "MARKETPLACE_FULFILL",

  PDV_SALE = "PDV_SALE",

  ESCROW_REQUEST = "ESCROW_REQUEST",
  ESCROW_PAID = "ESCROW_PAID",
  ESCROW_RELEASE = "ESCROW_RELEASE",

  CONTRACT_CREATE = "CONTRACT_CREATE",
  CONTRACT_SIGN = "CONTRACT_SIGN",
  CONTRACT_MILESTONE_VALIDATE = "CONTRACT_MILESTONE_VALIDATE",

  MILK_TANK_CHECK = "MILK_TANK_CHECK",
  MILK_COLLECTION_BUILD = "MILK_COLLECTION_BUILD",
  MILK_PRICE = "MILK_PRICE",
  MILK_ESCROW_PAY = "MILK_ESCROW_PAY",

  ASSET_BIRTH = "ASSET_BIRTH",
  ASSET_TRANSFER = "ASSET_TRANSFER"
}

// ===== RULESETS =====
export enum RuleSet {
  TENANT_ISOLATION = "TENANT_ISOLATION",
  IDENTITY_REQUIRED = "IDENTITY_REQUIRED",
  TRACEABILITY_REQUIRED = "TRACEABILITY_REQUIRED",
  STOCK_LIMITS = "STOCK_LIMITS",
  ENV_LIMITS = "ENV_LIMITS",
  ESCROW_REQUIRED = "ESCROW_REQUIRED",
  ESCROW_BEFORE_RESERVE = "ESCROW_BEFORE_RESERVE",
  SUPPLIER_SPLIT_BY_IDENTITY = "SUPPLIER_SPLIT_BY_IDENTITY",
  CANCEL_FEE = "CANCEL_FEE",
  GEO_RADIUS_EXPAND = "GEO_RADIUS_EXPAND",
  TEMPLATE_OR_AI_CONTRACT = "TEMPLATE_OR_AI_CONTRACT",
  DIGITAL_SIGNATURE_REQUIRED = "DIGITAL_SIGNATURE_REQUIRED",
  EVIDENCE_REQUIRED = "EVIDENCE_REQUIRED",
  MEMBERSHIP_REQUIRED = "MEMBERSHIP_REQUIRED",
  PRICING_FORMULA = "PRICING_FORMULA",
  ESCROW_SPLIT = "ESCROW_SPLIT",
  CHILD_FOLLOWS_MOTHER = "CHILD_FOLLOWS_MOTHER"
}

// ===== LOCKS =====
export enum LockType {
  CAR_BLOCK = "CAR_BLOCK",
  IE_BLOCK = "IE_BLOCK",
  ENV_LIMIT = "ENV_LIMIT",
  THIRD_PARTY_CUSTODY = "THIRD_PARTY_CUSTODY",
  NON_PAYMENT = "NON_PAYMENT",
  INVOICE_BLOCK = "INVOICE_BLOCK"
}

// ===== EVIDÊNCIA =====
export enum EvidenceType {
  TYPE_A = "TYPE_A",
  TYPE_B = "TYPE_B",
  WEBHOOK = "WEBHOOK",
  DIGITAL_SIGNATURE = "DIGITAL_SIGNATURE",
  DOCUMENT = "DOCUMENT"
}

// ===== ROLES =====
export enum Role {
  ADMIN = "ADMIN",
  MANAGER = "MANAGER",
  OPERATOR = "OPERATOR",
  PRODUCER = "PRODUCER",
  TECHNICIAN = "TECHNICIAN",
  SUPPLIER = "SUPPLIER",
  AUDITOR = "AUDITOR",
  LOGISTICS = "LOGISTICS",
  INVESTOR = "INVESTOR"
}
